# Отчет по лабораторной работе №3. NumPy

## Выполнение работы
В рамках лабораторной работы было выполнено:
1. Открыли файл в Google Colab (используйте собственный форк репозитория).
2. Решили задачи.
3. Сохранили результат в репозиторий github в директорию `./les03`.
4. Создали *pull request* в репозиторий: [https://github.com/chebotarevsa/dap-2024](https://github.com/chebotarevsa/dap-2024).
- Название pull request имеет формат: <Номер лабораторной работы> <Номер группы> <ФИО>.
5. Сдали работу в системе *Пегас*, в отчете указали ссылку на pull request.

**Ссылка на репозиторий GitHub (лабораторная работа №3): [https://github.com/ALEXANDER-ALLIS/dap-2024/tree/main/les03](https://github.com/ALEXANDER-ALLIS/dap-2024/tree/main/les03).**

In [7]:
import numpy as np
np.version.version

'2.0.2'

### Задание №1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)

In [6]:
import numpy as np

arr = np.random.randint(-1000, 1000, size=(10,10))

print(arr)

print("\nMin - " + str(np.min(arr)))
print("Max - " + str(np.max(arr)))

[[ 140 -998   -3 -997  214 -665 -540  805 -109 -571]
 [ -95 -508 -315  879 -172   24  132 -330 -886 -201]
 [-756  666 -480 -287  -92 -914 -246  770 -164 -914]
 [-644  167  658  206  237  824  346 -264  129  390]
 [-798  857  178 -952 -888  917  939  515 -405  -25]
 [ 346 -397  897  842  924  320  159  829 -447  408]
 [ 824  780   54  105  984 -241 -901 -558  546  118]
 [-469  106 -412 -180  470  500 -235  985 -851 -611]
 [ 647  485  913  354  173 -701 -896  455  -58  216]
 [-713 -337 -597 -647  -67 -864   75  902  -71 -464]]

Min - -998
Max - 985


### Задание №2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [8]:
import numpy as np

size = 8

arr = np.zeros((size,size))

for i in range(size):
  for j in range(size):
    if i % 2 != 0 and j % 2 != 0:
      continue
    if i % 2 != 0 or j % 2 != 0:
      arr[i,j] = 1

print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


### Задание №3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [9]:
import numpy as np

z = np.arange(11)

print("Исходный массив:" + str(z))

for i in range(z.size):
  if z[i] > 3 and z[i] < 8:
    z[i] *= -1

print("Итоговый массив:" + str(z))

Исходный массив:[ 0  1  2  3  4  5  6  7  8  9 10]
Итоговый массив:[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


### Задание №4. Найти среднее заначение строки матрицы и вычесть его из каждого елемента строки

In [14]:
import numpy as np

z = np.random.rand(5, 10)
average = np.mean(z, axis=1, keepdims=True)

print("Исходный массив\n" + str(z))
print("\nСреднее арифметическое\n" + str(average) + "\n")

print("Итоговый массив: \n" + str(np.subtract(z, average)))

Исходный массив
[[0.94932989 0.71952468 0.95192334 0.81183577 0.68685308 0.06850397
  0.51553368 0.09281534 0.67236415 0.64705716]
 [0.1103422  0.43318869 0.11095303 0.92095718 0.49873855 0.98280152
  0.28787848 0.03308295 0.09123831 0.30003281]
 [0.50981173 0.60232171 0.15896199 0.48963295 0.45011989 0.20750609
  0.94862279 0.58286848 0.77097771 0.57276789]
 [0.44805761 0.8465326  0.18007664 0.12350588 0.64147983 0.85646259
  0.82197823 0.83506665 0.3279669  0.03348735]
 [0.53173124 0.29542258 0.39043735 0.32695138 0.27239732 0.55743562
  0.78839751 0.24989983 0.18729013 0.55096516]]

Среднее арифметическое
[[0.61157411]
 [0.37692137]
 [0.52935912]
 [0.51146143]
 [0.41509281]]

Итоговый массив: 
[[ 0.33775579  0.10795058  0.34034924  0.20026166  0.07527897 -0.54307014
  -0.09604043 -0.51875877  0.06079004  0.03548306]
 [-0.26657917  0.05626732 -0.26596834  0.54403581  0.12181718  0.60588015
  -0.08904289 -0.34383842 -0.28568306 -0.07688856]
 [-0.01954739  0.07296259 -0.37039713 -0.039

### Задание №5. Поменяйте 1 и 2 строки матрицы

In [16]:
import numpy as np

z = np.arange(25).reshape(5,5)
print("Исходное:\n" + str(z))

tmp = z[0][:].copy()
z[0][:] = z[1][:]
z[1][:] = tmp

print("\nИтог:\n" + str(z))

Исходное:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Итог:
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### Задание №6. Дан массив 10x2 подеставлющий собой точки в декартовой системе координат, преобразовать в полярную

In [21]:
import numpy as np
import math

z = np.random.random((10,2))
res = z.copy()

res[:, 0] = np.sqrt(np.square(z[:, 0]) + np.square(z[:, 1]))
res[:, 1] = np.arctan2(z[:, 1], z[:, 0])

print("Исходное:\n", z)
print("\nРезультат (r, theta):\n", res)

Исходное:
 [[0.67915822 0.44476759]
 [0.70231589 0.6019346 ]
 [0.05510371 0.20534927]
 [0.15268866 0.26129408]
 [0.17862248 0.2193643 ]
 [0.4446045  0.91772497]
 [0.00460602 0.86376276]
 [0.14388165 0.29024382]
 [0.9580065  0.84849748]
 [0.31464454 0.98523947]]

Результат (r, theta):
 [[0.81183378 0.57979863]
 [0.92497183 0.70858486]
 [0.21261407 1.30863106]
 [0.30263579 1.04195949]
 [0.28288988 0.88741259]
 [1.01975109 1.11965477]
 [0.86377504 1.56546387]
 [0.3239497  1.11057309]
 [1.27973608 0.72485294]
 [1.03426206 1.26167546]]


### Задание №7. Заменить максимальный элемент массива на ноль

In [23]:
import numpy as np

z = np.random.random(10)
max = z.max()

print("Максимум:", max)
print("\nИсходное:\n", z)

z[(np.where(z == max))] = 0

print("\nРезультат:\n", z)

Максимум: 0.9062026189897148

Исходное:
 [0.58662533 0.53904012 0.7908138  0.12148205 0.26546753 0.90620262
 0.20148178 0.79226257 0.43040998 0.09072368]

Результат:
 [0.58662533 0.53904012 0.7908138  0.12148205 0.26546753 0.
 0.20148178 0.79226257 0.43040998 0.09072368]


### Задание №8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз

In [30]:
import numpy as np

z = np.ones(10)
i = np.random.randint(0,len(z),20)
chk = ""

print("Первый массив:\n", z)
print("\nВторой массив:\n", i)

for char in i:
  if str(char) in chk:
    continue
  else:
    z[char] += 1
    chk += str(char)

print("\nРезультат:\n", z)

Первый массив:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Второй массив:
 [7 7 3 9 0 8 9 0 9 7 9 6 4 3 5 9 5 0 0 0]

Результат:
 [2. 1. 1. 2. 2. 2. 2. 2. 2. 2.]


### Задание №9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [38]:
import numpy as np

z = np.array([1,2,3,4,5])
result = []

for i in range(z.size - 1):
    result.append(int(z[i]))
    result.append(0)
    result.append(0)
    result.append(0)

result.append(int(z[z.size-1]))

arr = np.array(result)
print("Исходное:\n", z)
print("\nРезультат:\n", result)

Исходное:
 [1 2 3 4 5]

Результат:
 [1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5]


### Задание №10. Найти ближайшее к заданному значению число в заданном массиве

In [54]:
import numpy as np

z = np.arange(100)
v = np.random.uniform(0,100)
chk = v - int(v)

print("Массив:\n", z)
print("\nИсходное число:\n", v)

print((z[int(v)], z[int(v) + 1])[chk > 0.5])

Массив:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

Исходное число:
 87.20670509214204
87
